# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory\
$git_branch$git_status\
$python\
$rust$golang$nodejs$java$ruby$c$kotlin$swift$dart$php$lua$zig\
${custom.progress}\
$line_break\
$character"""

[character]
success_symbol = '[➜](bold #a6e3a1)'
error_symbol = '[➜](bold #f38ba8)'

# integrate progress:
[custom.progress]
command = "progress -w"
when = "progress -q"
symbol = "🗂️  "
style = "bold #a6e3a1"
format = "$prefix[$output]($style)"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
style = "bold #89b4fa"

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "
style = "bold #89dceb"

[directory]
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = false
home_symbol = "  ~"
style = "bold #89b4fa"

[docker_context]
symbol = " "

[elixir]
symbol = " "
style = "bold #cba6f7"

[elm]
symbol = " "
style = "bold #89b4fa"

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
style = "bold #cba6f7"

[golang]
symbol = " "
style = "bold #89dceb"

[guix_shell]
symbol = " "

[haskell]
symbol = " "
style = "bold #cba6f7"

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
style = "bold #fab387"

[julia]
symbol = " "
style = "bold #cba6f7"

[kotlin]
symbol = " "
style = "bold #fab387"

[lua]
symbol = " "
style = "bold #89b4fa"

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "
style = "bold #f9e2af"

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = "bold #a6e3a1"

[ocaml]
symbol = " "
style = "bold #fab387"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "
style = "bold #89b4fa"

[php]
symbol = " "
style = "bold #b4befe"

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'
style = "bold #f9e2af"

[rlang]
symbol = "󰟔 "
style = "bold #89b4fa"

[ruby]
symbol = " "
style = "bold #f38ba8"

[rust]
symbol = " "
style = "bold #fab387"

[scala]
symbol = " "
style = "bold #f38ba8"

[swift]
symbol = " "
style = "bold #fab387"

[zig]
symbol = " "
style = "bold #fab387"
